export const menuList = [
    {
        title:'H O M E',
        key:'home',
        path:'/',
        icon:'HomeOutlined',
        content:'H O M E'
    },
    {
        title:'文章管理',
        key:'article-manage',
        icon:'HddOutlined',
        content:'文章管理',
        child:[
            {
                content:'文章列表',
                key:'article-list',
                path:'/article/list'
            },
            {
                content:'添加文章',
                key:'article-add',
                path:'/article/add'
            },
            {
                content:'草稿箱',
                key:'article-drafts',
                path:'/article/drafts'
            }
        ]
    },
    {
        title:'标签管理',
        key:'tag-manage',
        icon:'HddOutlined',
        content:'标签管理',
        child:[
            {
                content:'标签列表',
                key:'tag-list',
                path:'/tag/list'
            },
            {
                content:'添加标签',
                key:'tag-add',
                path:'/tag/add'
            }
        ]
    },
    {
        title:'乱七八糟',
        key:'source-manage',
        icon:'GithubOutlined',
        content:'乱七八糟',
        child:[
            {
                content:'fund管理',
                key:'fund-list',
                path:'/fund/list'
            }
        ]
    }
]